# Generated by Django 5.1.5 on 2025-01-29 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_tag_alter_shop_category_alter_shop_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=ckeditor.fields.RichTextField(default='NULL'),
            preserve_default=False,
        ),
    ]
