# Generated by Django 5.1.5 on 2025-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_product_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
